"""GOLDEN: FCStd parametric-tree import — true history recovery, proven.

Fixtures are synthetic .FCStd zips with realistic Document.xml trees AND the
matching embedded breps (generated by our own kernel), so the proof oracle is
exercised for real: the parametric rebuild must match the embedded geometry.
"""

from __future__ import annotations

import zipfile

import pytest

pytestmark = pytest.mark.occt

DOC_XML = """<?xml version='1.0' encoding='utf-8'?>
<Document SchemaVersion="4">
  <Objects Count="3">
    <Object name="Box" type="Part::Box"/>
    <Object name="Cylinder" type="Part::Cylinder"/>
    <Object name="Cut" type="Part::Cut"/>
  </Objects>
  <ObjectData Count="3">
    <Object name="Box">
      <Properties Count="4">
        <Property name="Length" type="App::PropertyLength"><Float value="60"/></Property>
        <Property name="Width" type="App::PropertyLength"><Float value="40"/></Property>
        <Property name="Height" type="App::PropertyLength"><Float value="8"/></Property>
        <Property name="Placement" type="App::PropertyPlacement">
          <PropertyPlacement Px="0" Py="0" Pz="0" A="0" Ox="0" Oy="0" Oz="1"/>
        </Property>
      </Properties>
    </Object>
    <Object name="Cylinder">
      <Properties Count="3">
        <Property name="Radius" type="App::PropertyLength"><Float value="3.2"/></Property>
        <Property name="Height" type="App::PropertyLength"><Float value="8"/></Property>
        <Property name="Placement" type="App::PropertyPlacement">
          <PropertyPlacement Px="15" Py="20" Pz="0" A="0" Ox="0" Oy="0" Oz="1"/>
        </Property>
      </Properties>
    </Object>
    <Object name="Cut">
      <Properties Count="2">
        <Property name="Base" type="App::PropertyLink"><Link value="Box"/></Property>
        <Property name="Tool" type="App::PropertyLink"><Link value="Cylinder"/></Property>
      </Properties>
    </Object>
  </ObjectData>
</Document>
"""


@pytest.fixture(scope="module")
def kernel():
    from gitcad.kernel.occt import OcctKernel

    return OcctKernel()


def _make_fcstd(tmp_path, kernel, xml: str, shape) -> str:
    """A synthetic .FCStd: Document.xml + the result shape's brep (the oracle)."""
    brep = str(tmp_path / "shape.brep")
    kernel.export_brep(shape, brep)
    path = tmp_path / "part.FCStd"
    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr("Document.xml", xml)
        zf.write(brep, "CutShape.brep")
    return str(path)


def test_parametric_tree_imports_and_proves(kernel, tmp_path) -> None:
    from gitcad.importers.fcstd_tree import import_fcstd_tree

    expected = kernel.boolean("cut", kernel.box(60, 40, 8),
                              kernel.transform(kernel.cylinder(3.2, 8), translate=(15, 20, 0)))
    path = _make_fcstd(tmp_path, kernel, DOC_XML, expected)

    doc, report = import_fcstd_tree(path, kernel, str(tmp_path / "assets"))
    assert report.format == "fcstd-parametric"
    assert report.imported["proof_residual_mm3"] < 1e-3
    # The tree is LIVE: real ops with real editable dimensions.
    ops = [f.op for f in doc.features]
    assert ops.count("box") == 1 and ops.count("cylinder") == 1 and ops.count("boolean") == 1
    params = {f.op: f.params for f in doc.features}
    assert params["cylinder"]["radius"] == 3.2
    # ...and it rebuilds to the exact imported volume.
    v = kernel.measure(doc.build(kernel).final(doc))["volume"]
    assert v == pytest.approx(kernel.measure(expected)["volume"], rel=1e-9)


def test_geometry_mismatch_falls_back_honestly(kernel, tmp_path) -> None:
    """Tree says one thing, embedded geometry another (corrupt/edited file) —
    the proof fails and the import falls back to geometry with the reason."""
    from gitcad.importers.fcstd_tree import import_fcstd_tree

    wrong_geometry = kernel.box(10, 10, 10)   # NOT what the tree builds
    path = _make_fcstd(tmp_path, kernel, DOC_XML, wrong_geometry)

    doc, report = import_fcstd_tree(path, kernel, str(tmp_path / "assets"))
    assert report.format == "fcstd"           # fell back
    assert any("does not match" in w for w in report.warnings)
    # The fallback still delivers the (authoritative) embedded geometry.
    v = kernel.measure(doc.build(kernel).final(doc))["volume"]
    assert v == pytest.approx(1000.0, rel=1e-6)


def test_unmapped_types_fall_back_honestly(kernel, tmp_path) -> None:
    """A PartDesign (sketch-based) object is out of v1 scope — fall back with
    the unmapped type named, never guess."""
    from gitcad.importers.fcstd_tree import import_fcstd_tree

    xml = DOC_XML.replace('type="Part::Cut"', 'type="PartDesign::Pad"')
    shape = kernel.box(60, 40, 8)
    path = _make_fcstd(tmp_path, kernel, xml, shape)

    _, report = import_fcstd_tree(path, kernel, str(tmp_path / "assets"))
    assert report.format == "fcstd"
    assert any("PartDesign::Pad" in w for w in report.warnings)
